test_lemmatized_text = [
    {
        "word": "Arma",
        "glossed": "na",
        "lemma_id": None,
        "resolved": "no-lemma",
        "following": " ",
        "gloss_ids": [],
        "word_normalized": "Arma",
    },
    {
        "word": "virum",
        "glossed": "na",
        "lemma_id": None,
        "resolved": "no-lemma",
        "following": "",
        "gloss_ids": [],
        "word_normalized": "virum",
    },
    {
        "word": "que",
        "glossed": "na",
        "lemma_id": None,
        "resolved": "no-lemma",
        "following": " ",
        "gloss_ids": [],
        "word_normalized": "que",
    },
    {
        "word": "canō",
        "glossed": "na",
        "lemma_id": None,
        "resolved": "no-lemma",
        "following": ", ",
        "gloss_ids": [],
        "word_normalized": "cano",
    },
    {
        "word": "Trōiae",
        "glossed": "na",
        "lemma_id": None,
        "resolved": "no-lemma",
        "following": " ",
        "gloss_ids": [],
        "word_normalized": "Troiae",
    },
    {
        "word": "quī",
        "glossed": "na",
        "lemma_id": None,
        "resolved": "no-lemma",
        "following": " ",
        "gloss_ids": [],
        "word_normalized": "qui",
    },
    {
        "word": "prīmus",
        "glossed": "na",
        "lemma_id": None,
        "resolved": "no-lemma",
        "following": " ",
        "gloss_ids": [],
        "word_normalized": "primus",
    },
    {
        "word": "ab",
        "glossed": "na",
        "lemma_id": None,
        "resolved": "no-lemma",
        "following": " ",
        "gloss_ids": [],
        "word_normalized": "ab",
    },
    {
        "word": "ōrīs",
        "glossed": "na",
        "lemma_id": None,
        "resolved": "no-lemma",
        "following": "\r\n",
        "gloss_ids": [],
        "word_normalized": "oris",
    },
    {
        "word": "Ītaliam",
        "glossed": "na",
        "lemma_id": None,
        "resolved": "no-lemma",
        "following": ", ",
        "gloss_ids": [],
        "word_normalized": "Italiam",
    },
    {
        "word": "fātō",
        "glossed": "na",
        "lemma_id": None,
        "resolved": "no-lemma",
        "following": " ",
        "gloss_ids": [],
        "word_normalized": "fato",
    },
    {
        "word": "profugus",
        "glossed": "na",
        "lemma_id": None,
        "resolved": "no-lemma",
        "following": ", ",
        "gloss_ids": [],
        "word_normalized": "profugus",
    },
    {
        "word": "Lāvīniaque",
        "glossed": "na",
        "lemma_id": None,
        "resolved": "no-lemma",
        "following": " ",
        "gloss_ids": [],
        "word_normalized": "Laviniaque",
    },
    {
        "word": "vēnit",
        "glossed": "na",
        "lemma_id": None,
        "resolved": "no-lemma",
        "following": " ",
        "gloss_ids": [],
        "word_normalized": "venit",
    },
]
test_original_text = """Arma virumque canō, Trōiae quī prīmus ab ōrīs\r\nĪtaliam, fātō profugus, Lāvīniaque vēnit"""
test_original_text_html = '<p><span gloss_ids="[]" glossed="na" lemma_id="None" resolved="no-lemma" word_normalized="Arma">Arma</span><span follower="true"> </span><span gloss_ids="[]" glossed="na" lemma_id="None" resolved="no-lemma" word_normalized="virum">virum</span><span follower="true"></span><span gloss_ids="[]" glossed="na" lemma_id="None" resolved="no-lemma" word_normalized="que">que</span><span follower="true"> </span><span gloss_ids="[]" glossed="na" lemma_id="None" resolved="no-lemma" word_normalized="cano">canō</span><span follower="true">, </span><span gloss_ids="[]" glossed="na" lemma_id="None" resolved="no-lemma" word_normalized="Troiae">Trōiae</span><span follower="true"> </span><span gloss_ids="[]" glossed="na" lemma_id="None" resolved="no-lemma" word_normalized="qui">quī</span><span follower="true"> </span><span gloss_ids="[]" glossed="na" lemma_id="None" resolved="no-lemma" word_normalized="primus">prīmus</span><span follower="true"> </span><span gloss_ids="[]" glossed="na" lemma_id="None" resolved="no-lemma" word_normalized="ab">ab</span><span follower="true"> </span><span gloss_ids="[]" glossed="na" lemma_id="None" resolved="no-lemma" word_normalized="oris">ōrīs</span><span follower="true"><br/></span><span gloss_ids="[]" glossed="na" lemma_id="None" resolved="no-lemma" word_normalized="Italiam">Ītaliam</span><span follower="true">, </span><span gloss_ids="[]" glossed="na" lemma_id="None" resolved="no-lemma" word_normalized="fato">fātō</span><span follower="true"> </span><span gloss_ids="[]" glossed="na" lemma_id="None" resolved="no-lemma" word_normalized="profugus">profugus</span><span follower="true">, </span><span gloss_ids="[]" glossed="na" lemma_id="None" resolved="no-lemma" word_normalized="Laviniaque">Lāvīniaque</span><span follower="true"> </span><span gloss_ids=[] glossed="na" lemma_id="None" resolved="no-lemma" word_normalized="venit">vēnit</span><span follower="true"> </span></p>'
