test_lemmatized_text = [
    {
        "word": "Arma",
        "glossed": "glossed-automatic",
        "lemma_id": 1372,
        "resolved": "no-ambiguity",
        "following": " ",
        "gloss_ids": [84128, 68154],
        "word_normalized": "Arma",
        "initial": "",
    },
    {
        "word": "virum",
        "glossed": "glossed-automatic",
        "lemma_id": 1310,
        "resolved": "no-ambiguity",
        "following": "",
        "gloss_ids": [83435, 86346],
        "word_normalized": "virum",
        "initial": "",
    },
    {
        "word": "que",
        "glossed": "glossed-automatic",
        "lemma_id": 1068,
        "resolved": "no-ambiguity",
        "following": " ",
        "gloss_ids": [79758],
        "word_normalized": "que",
        "initial": "",
    },
    {
        "word": "canō",
        "glossed": "glossed-automatic",
        "lemma_id": 1913,
        "resolved": "no-ambiguity",
        "following": ", ",
        "gloss_ids": [68837],
        "word_normalized": "cano",
        "initial": "",
    },
    {
        "word": "Trōiae",
        "glossed": "glossed-automatic",
        "lemma_id": 50164,
        "resolved": "no-ambiguity",
        "following": " ",
        "gloss_ids": [82748],
        "word_normalized": "Troiae",
        "initial": "",
    },
    {
        "word": "quī",
        "glossed": "glossed-automatic",
        "lemma_id": 41276,
        "resolved": "no-ambiguity",
        "following": " ",
        "gloss_ids": [79774],
        "word_normalized": "qui",
        "initial": "",
    },
    {
        "word": "prīmus",
        "glossed": "glossed-automatic",
        "lemma_id": 1280,
        "resolved": "no-ambiguity",
        "following": " ",
        "gloss_ids": [85717, 79130],
        "word_normalized": "primus",
        "initial": "",
    },
    {
        "word": "ab",
        "glossed": "glossed-automatic",
        "lemma_id": 1239,
        "resolved": "no-ambiguity",
        "following": " ",
        "gloss_ids": [83603, 83604, 66883],
        "word_normalized": "ab",
        "initial": "",
    },
    {
        "word": "ōrīs",
        "glossed": "glossed-automatic",
        "lemma_id": 1415,
        "resolved": "no-ambiguity",
        "following": "\r\n",
        "gloss_ids": [85502, 77462],
        "word_normalized": "oris",
        "initial": "",
    },
    {
        "word": "Ītaliam",
        "glossed": "glossed-automatic",
        "lemma_id": 27293,
        "resolved": "no-ambiguity",
        "following": ", ",
        "gloss_ids": [85202],
        "word_normalized": "Italiam",
        "initial": "",
    },
    {
        "word": "fātō",
        "glossed": "glossed-automatic",
        "lemma_id": 1585,
        "resolved": "no-ambiguity",
        "following": " ",
        "gloss_ids": [72637, 85017],
        "word_normalized": "fato",
        "initial": "",
    },
    {
        "word": "profugus",
        "glossed": "glossed-automatic",
        "lemma_id": 39952,
        "resolved": "no-ambiguity",
        "following": ", ",
        "gloss_ids": [79267],
        "word_normalized": "profugus",
        "initial": "",
    },
    {
        "word": "Lāvīniaque",
        "glossed": "glossed-automatic",
        "lemma_id": None,
        "resolved": "no-ambiguity",
        "following": " ",
        "gloss_ids": [],
        "word_normalized": "Laviniaque",
        "initial": "",
    },
    {
        "word": "vēnit",
        "glossed": "glossed-automatic",
        "lemma_id": 1299,
        "resolved": "no-ambiguity",
        "following": " ",
        "gloss_ids": [83198],
        "word_normalized": "venit",
        "initial": "",
    },
]

test_original_text = """Arma virumque canō, Trōiae quī prīmus ab ōrīs\r\nĪtaliam, fātō profugus, Lāvīniaque vēnit"""
