# Generated by Django 2.1.4 on 2018-12-13 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FormToLemma',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('context', models.CharField(blank=True, max_length=255)),
                ('lang', models.CharField(max_length=3)),
                ('form', models.CharField(max_length=255)),
                ('lemma', models.CharField(max_length=255)),
            ],
        ),
    ]
