# Generated by Django 2.2 on 2019-06-18 21:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lemmatization', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='formtolemma',
            name='lang',
            field=models.CharField(choices=[('grc', 'Ancient Greek'), ('lat', 'Latin'), ('rus', 'Russian')], max_length=3),
        ),
    ]
