# Generated by Django 3.2.9 on 2022-02-03 20:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lemmatization', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='LatinLexicon',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.CharField(max_length=255)),
                ('lemma', models.CharField(max_length=255)),
                ('frequency', models.IntegerField(default=0)),
            ],
        ),
        migrations.AddConstraint(
            model_name='latinlexicon',
            constraint=models.UniqueConstraint(fields=('token', 'lemma'), name='unique_token_lemma'),
        ),
    ]
