# Generated by Django 3.2.9 on 2022-02-28 20:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lemmatization', '0002_auto_20220203_2026'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='latinlexicon',
            name='frequency',
        ),
        migrations.AddField(
            model_name='latinlexicon',
            name='count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='latinlexicon',
            name='rank',
            field=models.IntegerField(default=999999),
        ),
        migrations.AddField(
            model_name='latinlexicon',
            name='rate',
            field=models.FloatField(default=0),
        ),
    ]
