# Generated by Django 3.2.12 on 2022-05-18 13:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lemmatization', '0003_auto_20220228_2024'),
    ]

    operations = [
        migrations.CreateModel(
            name='Gloss',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gloss', models.TextField(max_length=1024)),
            ],
        ),
        migrations.CreateModel(
            name='Lemma',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lang', models.CharField(max_length=3)),
                ('lemma', models.CharField(max_length=255)),
                ('alt_lemma', models.CharField(db_index=True, max_length=255)),
                ('label', models.CharField(max_length=255)),
                ('rank', models.IntegerField(default=999999)),
                ('count', models.IntegerField(default=0)),
                ('rate', models.FloatField(default=0)),
            ],
        ),
        migrations.RemoveField(
            model_name='formtolemma',
            name='context',
        ),
        migrations.AddConstraint(
            model_name='formtolemma',
            constraint=models.UniqueConstraint(fields=('lang', 'form', 'lemma'), name='unique_lang_form_lemma'),
        ),
        migrations.AddConstraint(
            model_name='lemma',
            constraint=models.UniqueConstraint(fields=('lemma', 'lang'), name='unique_lemma_lang'),
        ),
        migrations.AddField(
            model_name='gloss',
            name='lemma',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='glosses', to='lemmatization.lemma'),
        ),
        migrations.AlterField(
            model_name='formtolemma',
            name='lemma',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='forms', to='lemmatization.lemma'),
        ),
    ]
