# Generated by Django 3.2.15 on 2022-09-15 21:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lemmatization', '0004_auto_20220518_1349'),
    ]

    operations = [
        migrations.DeleteModel(
            name='LatinLexicon',
        ),
    ]
