# Generated by Django 3.2.22 on 2024-07-15 05:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lemmatization', '0006_auto_20231006_0128'),
        ('lemmatization', '0006_auto_20240216_0533'),
    ]

    operations = [
    ]
