# Generated by Django 2.1.2 on 2018-11-06 19:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='VocabularyList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('cloned_from', models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, to='vocab_list.VocabularyList')),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'vocabulary list',
            },
        ),
        migrations.CreateModel(
            name='VocabularyListEntry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lemma', models.CharField(max_length=255)),
                ('gloss', models.TextField(blank=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('vocabulary_list', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entries', to='vocab_list.VocabularyList')),
            ],
            options={
                'verbose_name': 'vocabulary list entry',
                'verbose_name_plural': 'vocabulary list entries',
            },
        ),
        migrations.AlterOrderWithRespectTo(
            name='vocabularylistentry',
            order_with_respect_to='vocabulary_list',
        ),
    ]
