# Generated by Django 2.1.4 on 2019-01-31 09:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lemma_lattices', '0003_auto_20181213_1129'),
        ('vocab_list', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='vocabularylistentry',
            old_name='lemma',
            new_name='headword',
        ),
        migrations.AddField(
            model_name='vocabularylistentry',
            name='node',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='lemma_lattices.LemmaLatticeNode'),
        ),
        migrations.AlterUniqueTogether(
            name='vocabularylistentry',
            unique_together={('vocabulary_list', 'headword')},
        ),
    ]
