# Generated by Django 2.1.7 on 2019-02-28 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vocab_list', '0002_auto_20190201_1127'),
    ]

    operations = [
        migrations.AddField(
            model_name='vocabularylist',
            name='lang',
            field=models.CharField(default='grc', max_length=3),
            preserve_default=False,
        ),
    ]
