# Generated by Django 2.1.7 on 2019-03-12 18:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lattices', '0002_auto_20190214_1557'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('vocab_list', '0003_vocabularylist_lang'),
    ]

    operations = [
        migrations.CreateModel(
            name='PersonalVocabularyList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lang', models.CharField(max_length=3)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'vocabulary list',
            },
        ),
        migrations.CreateModel(
            name='PersonalVocabularyListEntry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('headword', models.CharField(max_length=255)),
                ('gloss', models.TextField(blank=True)),
                ('familiarity', models.IntegerField(null=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('node', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='lattices.LatticeNode')),
                ('vocabulary_list', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entries', to='vocab_list.PersonalVocabularyList')),
            ],
            options={
                'verbose_name': 'personal vocabulary list entry',
                'verbose_name_plural': 'personal vocabulary list entries',
            },
        ),
        migrations.AlterField(
            model_name='vocabularylistentry',
            name='node',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='vocabulary_entries', to='lattices.LatticeNode'),
        ),
        migrations.AlterUniqueTogether(
            name='personalvocabularylistentry',
            unique_together={('vocabulary_list', 'headword')},
        ),
        migrations.AlterOrderWithRespectTo(
            name='personalvocabularylistentry',
            order_with_respect_to='vocabulary_list',
        ),
        migrations.AlterUniqueTogether(
            name='personalvocabularylist',
            unique_together={('user', 'lang')},
        ),
    ]
