# Generated by Django 2.2 on 2019-04-01 23:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('vocab_list', '0004_auto_20190312_1841'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='personalvocabularylist',
            options={'verbose_name': 'personal vocabulary list'},
        ),
        migrations.AlterField(
            model_name='personalvocabularylistentry',
            name='node',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='lattices.LatticeNode'),
        ),
    ]
