# Generated by Django 2.2 on 2019-04-04 21:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vocab_list', '0006_personalvocabularystats'),
    ]

    operations = [
        migrations.AlterField(
            model_name='personalvocabularystats',
            name='five',
            field=models.DecimalField(decimal_places=4, default='0', max_digits=5),
        ),
        migrations.AlterField(
            model_name='personalvocabularystats',
            name='four',
            field=models.DecimalField(decimal_places=4, default='0', max_digits=5),
        ),
        migrations.AlterField(
            model_name='personalvocabularystats',
            name='one',
            field=models.DecimalField(decimal_places=4, default='0', max_digits=5),
        ),
        migrations.AlterField(
            model_name='personalvocabularystats',
            name='three',
            field=models.DecimalField(decimal_places=4, default='0', max_digits=5),
        ),
        migrations.AlterField(
            model_name='personalvocabularystats',
            name='two',
            field=models.DecimalField(decimal_places=4, default='0', max_digits=5),
        ),
        migrations.AlterField(
            model_name='personalvocabularystats',
            name='unranked',
            field=models.DecimalField(decimal_places=4, default='0', max_digits=5),
        ),
    ]
