# Generated by Django 2.2.3 on 2019-11-15 21:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vocab_list', '0007_auto_20190404_2141'),
    ]

    operations = [
        migrations.AddField(
            model_name='vocabularylistentry',
            name='link_job_ended',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='vocabularylistentry',
            name='link_job_id',
            field=models.CharField(blank=True, max_length=250),
        ),
        migrations.AddField(
            model_name='vocabularylistentry',
            name='link_job_started',
            field=models.DateTimeField(null=True),
        ),
    ]
