# Generated by Django 3.2.12 on 2022-03-11 21:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vocab_list', '0010_alter_vocabularylistentry_unique_together'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='personalvocabularylistentry',
            unique_together=set(),
        ),
    ]
