# Generated by Django 3.2.15 on 2022-09-12 15:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lemmatization', '0004_auto_20220518_1349'),
        ('vocab_list', '0011_alter_personalvocabularylistentry_unique_together'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='personalvocabularylistentry',
            name='node',
        ),
        migrations.RemoveField(
            model_name='vocabularylistentry',
            name='node',
        ),
        migrations.AddField(
            model_name='personalvocabularylistentry',
            name='lemma',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='lemmatization.lemma'),
        ),
        migrations.AddField(
            model_name='vocabularylistentry',
            name='lemma',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='lemmatization.lemma'),
        ),
        migrations.AlterField(
            model_name='personalvocabularylistentry',
            name='gloss',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='lemmatization.gloss'),
        ),
        migrations.AlterField(
            model_name='vocabularylistentry',
            name='gloss',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='lemmatization.gloss'),
        ),
    ]
