# Generated by Django 3.2.15 on 2022-09-13 20:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lemmatization', '0004_auto_20220518_1349'),
        ('vocab_list', '0011_alter_personalvocabularylistentry_unique_together'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vocabularylistentry',
            name='node',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='vocabulary_entries', to='lemmatization.lemma'),
        ),
    ]
