# Generated by Django 3.2.15 on 2022-09-14 19:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vocab_list', '0012_auto_20220912_1535'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='personalvocabularylistentry',
            name='gloss',
        ),
        migrations.RemoveField(
            model_name='vocabularylistentry',
            name='gloss',
        ),
        migrations.AddField(
            model_name='personalvocabularylistentry',
            name='definition',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='vocabularylistentry',
            name='definition',
            field=models.TextField(blank=True),
        ),
    ]
