# Generated by Django 3.2.15 on 2022-09-13 20:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vocab_list', '0012_alter_vocabularylistentry_node'),
    ]

    operations = [
        migrations.RenameField(
            model_name='vocabularylistentry',
            old_name='node',
            new_name='lemma',
        ),
    ]
