# Generated by Django 3.2.15 on 2022-09-15 13:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lemmatization', '0004_auto_20220518_1349'),
        ('vocab_list', '0013_rename_node_vocabularylistentry_lemma'),
    ]

    operations = [
        migrations.RenameField(
            model_name='personalvocabularylistentry',
            old_name='gloss',
            new_name='definition',
        ),
        migrations.RenameField(
            model_name='vocabularylistentry',
            old_name='gloss',
            new_name='definition',
        ),
        migrations.AlterField(
            model_name='vocabularylistentry',
            name='lemma',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='lemmatization.lemma'),
        ),
    ]
