# Generated by Django 3.2.19 on 2024-02-16 05:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('vocab_list', '0014_alter_personalvocabularylistentry_familiarity'),
    ]

    operations = [
        migrations.CreateModel(
            name='Folder',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('data', models.JSONField()),
                ('personal_vocab_list', models.ManyToManyField(to='vocab_list.PersonalVocabularyList')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('vocab_lists', models.ManyToManyField(to='vocab_list.VocabularyList')),
            ],
            options={
                'verbose_name': 'vocabulary list folder',
                'verbose_name_plural': 'vocabulary list folders',
            },
        ),
    ]
