# Generated by Django 3.2.19 on 2024-02-16 05:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vocab_list', '0015_folder'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='folder',
            name='data',
        ),
    ]
