# Generated by Django 3.2.19 on 2024-02-16 05:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vocab_list', '0016_remove_folder_data'),
    ]

    operations = [
        migrations.AlterField(
            model_name='folder',
            name='personal_vocab_list',
            field=models.ManyToManyField(blank=True, to='vocab_list.PersonalVocabularyList'),
        ),
        migrations.AlterField(
            model_name='folder',
            name='vocab_lists',
            field=models.ManyToManyField(blank=True, to='vocab_list.VocabularyList'),
        ),
    ]
