# Generated by Django 3.2.19 on 2024-02-29 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vocab_list', '0017_auto_20240216_0542'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='folder',
            name='personal_vocab_list',
        ),
        migrations.RemoveField(
            model_name='folder',
            name='vocab_lists',
        ),
        migrations.AddField(
            model_name='personalvocabularylist',
            name='folder',
            field=models.ManyToManyField(blank=True, to='vocab_list.Folder'),
        ),
        migrations.AddField(
            model_name='vocabularylist',
            name='folder',
            field=models.ManyToManyField(blank=True, to='vocab_list.Folder'),
        ),
    ]
