# Generated by Django 3.2.19 on 2024-04-17 20:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vocab_list', '0018_auto_20240229_1738'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='personalvocabularylist',
            name='folder',
        ),
        migrations.RemoveField(
            model_name='vocabularylist',
            name='folder',
        ),
        migrations.AddField(
            model_name='folder',
            name='vocab_lists',
            field=models.ManyToManyField(blank=True, to='vocab_list.VocabularyList'),
        ),
    ]
