# Generated by Django 2.1.2 on 2018-12-13 11:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lemma_lattices', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FormNode',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('form', models.CharField(max_length=255)),
                ('node', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='form_strings', to='lemma_lattices.LemmaLatticeNode')),
            ],
        ),
        migrations.CreateModel(
            name='LemmaNode',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lemma', models.CharField(max_length=255)),
                ('node', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lemma_strings', to='lemma_lattices.LemmaLatticeNode')),
            ],
        ),
        migrations.CreateModel(
            name='NodeGloss',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gloss', models.TextField()),
                ('node', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='glosses', to='lemma_lattices.LemmaLatticeNode')),
            ],
        ),
    ]
