# Generated by Django 2.1.4 on 2018-12-13 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lemma_lattices', '0002_formnode_lemmanode_nodegloss'),
    ]

    operations = [
        migrations.AddField(
            model_name='formnode',
            name='context',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='lemmanode',
            name='context',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
