# Generated by Django 2.1.5 on 2019-02-01 11:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vocab_list', '0002_auto_20190131_0949'),
        ('lemma_lattices', '0003_auto_20181213_1129'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='LemmaLatticeNode',
            new_name='LatticeNode',
        ),
    ]
