version: '3'

services:
  db:
    image: postgres:latest
    restart: unless-stopped
    volumes:
        - postgres-data:/var/lib/postgresql/data
    environment:
        POSTGRES_USER: postgres
        POSTGRES_PASSWORD: postgres
        POSTGRES_DB: hedera

  redis:
    image: redis:latest
    restart: unless-stopped

  worker:
    build:
        context: ..
        dockerfile: .devcontainer/Dockerfile.worker
    environment:
        DATABASE_URL: postgres://postgres:postgres@db:5432/hedera
        REDIS_URL: redis://redis:6379/
    volumes:
        - ..:/workspace:cached
    command: python manage.py rqworker ${RQ_QUEUES:-default}
    depends_on:
        - db
        - redis

  webpack:
    build:
        context: ..
        dockerfile: .devcontainer/Dockerfile.webpack
    volumes:
        - ..:/workspace:cached
        - webpack-stats:/webpack-stats
    command: npm start
    ports:
      - 8080:8080

  app:
    build:
      context: ..
      dockerfile: .devcontainer/Dockerfile.web
    volumes:
      - ..:/workspace:cached
      - webpack-stats:/workspace/webpack-stats
    environment:
        DATABASE_URL: postgres://postgres:postgres@db:5432/hedera
        REDIS_URL: redis://redis:6379/
    entrypoint: ./.devcontainer/entrypoint.sh
    command: python manage.py runserver 0.0.0.0:8000
    ports:
      - 8000:8000
    depends_on:
        - db
        - redis
        - webpack
volumes:
  postgres-data:
  webpack-stats:
