# Generated by Django 2.2 on 2019-06-18 21:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserRole',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('student', 'Student in a Class'), ('learner', 'Lifelong Learner'), ('teacher', 'Teacher'), ('langadmin', 'Language Admin'), ('superadmin', 'Super user')], max_length=10)),
                ('lang', models.CharField(choices=[('grc', 'Ancient Greek'), ('lat', 'Latin'), ('rus', 'Russian')], max_length=3)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'role', 'lang')},
            },
        ),
    ]
