# Generated by Django 2.2.13 on 2020-08-27 17:03

from django.db import migrations


def default_profiles(apps, schema_editor):
    Profile = apps.get_model("hedera", "Profile")
    User = apps.get_model("auth", "User")
    for user in User.objects.all():
        Profile.objects.create(user=user)


class Migration(migrations.Migration):

    dependencies = [
        ('hedera', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(default_profiles)
    ]
