# Generated by Django 2.2.13 on 2020-08-27 19:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hedera', '0002_auto_20200827_1703'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='show_node_ids',
            field=models.CharField(choices=[('always', 'Always show node id'), ('never', 'Never show node id'), ('toggle', 'Let me toggle the reveal of node ids')], default='never', max_length=10),
        ),
    ]
