# Generated by Django 3.2.3 on 2021-07-19 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hedera', '0003_profile_show_node_ids'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='lang',
            field=models.CharField(max_length=3, null=True),
        ),
    ]
