# Generated by Django 2.1.5 on 2019-02-14 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lattices', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='latticenode',
            name='children',
            field=models.ManyToManyField(related_name='parents', to='lattices.LatticeNode'),
        ),
    ]
