# Generated by Django 3.2.12 on 2022-03-24 19:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lattices', '0004_latticenode_gloss'),
    ]

    operations = [
        migrations.DeleteModel(
            name='FormNode',
        ),
    ]
