# Generated by Django 3.2.12 on 2022-04-22 20:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lattices', '0005_delete_formnode'),
    ]

    operations = [
        migrations.AddField(
            model_name='lemmanode',
            name='count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='lemmanode',
            name='lang',
            field=models.CharField(choices=[('grc', 'Ancient Greek'), ('lat', 'Latin'), ('rus', 'Russian'), ('zho', 'Chinese')], default=None, max_length=3, null=True),
        ),
        migrations.AddField(
            model_name='lemmanode',
            name='rank',
            field=models.IntegerField(default=999999),
        ),
        migrations.AddField(
            model_name='lemmanode',
            name='rate',
            field=models.FloatField(default=0),
        ),
    ]
