# Generated by Django 2.2.12 on 2020-06-03 19:21

from django.conf import settings
from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('lemmatized_text', '0009_lemmatizedtext_original_text'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('vocab_list', '0008_auto_20191115_2132'),
    ]

    operations = [
        migrations.CreateModel(
            name='Group',
            fields=[
                ('class_key', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('student_invite_key', models.UUIDField(default=uuid.uuid4)),
                ('teacher_invite_key', models.UUIDField(default=uuid.uuid4)),
                ('students', models.ManyToManyField(related_name='enrolled_classes', to=settings.AUTH_USER_MODEL)),
                ('teachers', models.ManyToManyField(related_name='taught_classes', to=settings.AUTH_USER_MODEL)),
                ('texts', models.ManyToManyField(related_name='classes', to='lemmatized_text.LemmatizedText')),
                ('vocab_lists', models.ManyToManyField(related_name='classes', to='vocab_list.VocabularyList')),
            ],
        ),
    ]
