# Generated by Django 2.1.5 on 2019-02-14 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lemmatized_text', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='lemmatizedtext',
            name='title',
            field=models.CharField(default='missing', max_length=100),
            preserve_default=False,
        ),
    ]
