# Generated by Django 2.1.7 on 2019-03-12 16:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lemmatized_text', '0003_lemmatizedtext_lang'),
    ]

    operations = [
        migrations.AddField(
            model_name='lemmatizedtext',
            name='cloned_from',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='lemmatized_text.LemmatizedText'),
        ),
    ]
