# Generated by Django 2.1.7 on 2019-03-12 16:44

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lemmatized_text', '0004_lemmatizedtext_cloned_from'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lemmatizedtext',
            name='data',
            field=django.contrib.postgres.fields.jsonb.JSONField(),
        ),
    ]
