# Generated by Django 2.2.3 on 2019-08-28 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lemmatized_text', '0007_auto_20190827_1547'),
    ]

    operations = [
        migrations.AddField(
            model_name='lemmatizedtext',
            name='current_job',
            field=models.CharField(blank=True, max_length=250),
        ),
    ]
