# Generated by Django 2.2.3 on 2019-08-28 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lemmatized_text', '0008_lemmatizedtext_current_job'),
    ]

    operations = [
        migrations.AddField(
            model_name='lemmatizedtext',
            name='original_text',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
    ]
