# Generated by Django 2.2.16 on 2020-09-28 14:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('lattices', '0004_latticenode_gloss'),
        ('lemmatized_text', '0010_lemmatizedtext_cloned_for'),
    ]

    operations = [
        migrations.CreateModel(
            name='LemmatizationLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token_index', models.IntegerField()),
                ('resolved', models.BooleanField()),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('node', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lattices.LatticeNode')),
                ('text', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logs', to='lemmatized_text.LemmatizedText')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
