# Generated by Django 2.2.16 on 2020-09-28 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lemmatized_text', '0011_lemmatizationlog'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lemmatizationlog',
            name='resolved',
            field=models.CharField(max_length=100),
        ),
    ]
