# Generated by Django 2.2.16 on 2020-10-12 23:28
import uuid

from django.db import migrations

def secrets(apps, schema_editor):
    LemmatizedText = apps.get_model("lemmatized_text", "LemmatizedText")

    for text in LemmatizedText.objects.all():
        text.secret_id = uuid.uuid4()
        text.save()


class Migration(migrations.Migration):

    dependencies = [
        ('lemmatized_text', '0013_lemmatizedtext_secret_id'),
    ]

    operations = [
        migrations.RunPython(secrets)
    ]
