# Generated by Django 3.2.5 on 2021-07-29 21:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("groups", "0006_auto_20200726_1934"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("lemmatized_text", "0014_auto_20201012_2328"),
    ]

    operations = [
        migrations.AlterField(
            model_name="lemmatizedtext",
            name="cloned_for",
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to="groups.group"),
        ),
        migrations.CreateModel(
            name="LemmatizedTextBookmark",
            fields=[
                ("id", models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("text", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="lemmatized_text.lemmatizedtext")),
                ("user", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                "verbose_name": "lemmatized text bookmark",
                "verbose_name_plural": "lemmatized text bookmarks",
            },
        ),
        migrations.AddConstraint(
            model_name="lemmatizedtextbookmark",
            constraint=models.UniqueConstraint(fields=("user", "text"), name="unique_lemmatized_text_bookmark"),
        ),
    ]
