# Generated by Django 3.2.3 on 2021-07-19 17:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0006_auto_20200726_1934'),
        ('lemmatized_text', '0014_auto_20201012_2328'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lemmatizedtext',
            name='cloned_for',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='groups.group'),
        ),
    ]
