# Generated by Django 3.2.5 on 2021-08-12 20:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lemmatized_text', '0015_alter_lemmatizedtext_cloned_for'),
        ('lemmatized_text', '0015_auto_20210729_2109'),
    ]

    operations = [
    ]
