# Generated by Django 3.2.13 on 2022-09-06 19:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lemmatized_text', '0017_auto_20210908_1808'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lemmatizationlog',
            name='node',
        ),
    ]
