# Generated by Django 3.2.19 on 2023-10-06 01:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lemmatized_text', '0019_lemmatizationlog_lemma'),
    ]

    operations = [
        migrations.AddField(
            model_name='lemmatizedtextbookmark',
            name='read_status',
            field=models.BooleanField(default=False),
        ),
    ]
