# Generated by Django 3.2.22 on 2024-07-15 05:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lemmatized_text', '0021_lemmatizedtextbookmark_started_read_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='lemmatizedtextbookmark',
            name='ended_read_at',
            field=models.DateTimeField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='lemmatizedtextbookmark',
            name='started_read_at',
            field=models.DateTimeField(blank=True, default=None, null=True),
        ),
    ]
