# Generated by Django 3.2.19 on 2024-01-04 22:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lemmatized_text', '0022_alter_lemmatizedtextbookmark_started_read_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='lemmatizedtextbookmark',
            name='ended_read_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
