# Generated by Django 3.2.13 on 2024-02-26 20:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lemmatized_text', '0023_lemmatizedtextbookmark_ended_read_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lemmatizedtextbookmark',
            name='ended_read_at',
            field=models.DateTimeField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='lemmatizedtextbookmark',
            name='started_read_at',
            field=models.DateTimeField(blank=True, default=None, null=True),
        ),
    ]
