name: Code Checks
on: [push]
jobs:
  qa:
    name: Check builds and code quality
    runs-on: ubuntu-latest

    steps:
        - uses: actions/checkout@v2

        - name: Setup Python
          uses: actions/setup-python@v2
          with:
            python-version: '3.10'

        - uses: actions/setup-node@v2
          with:
            node-version: '14'

        - name: Cache Python dependencies
          id: cache
          uses: actions/cache@v2
          with:
            path: ~/.cache/pip
            key: ${{ runner.os }}-pip-${{ hashFiles('**/**/requirements/dev.txt' ) }}
            restore-keys: |
              ${{ runner.os }}-pip-

        - name: Cache node modules
          uses: actions/cache@v2
          with:
            path: ~/.npm
            key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
            restore-keys: |
              ${{ runner.os }}-node-

        - name: Setup flake8 annotations
          uses: rbialon/flake8-annotations@v1

        - name: Install Python Dependences
          run: |
            pip install -r hedera/requirements/dev.txt

        - name: Run linting and import sorting
          run: |
            isort -c **/*.py
            flake8 --show-source hedera lattices lemmatization lemmatized_text vocab_list lti

        - name: Install Static Dependences
          run: npm i --include=dev

        - name: Lint JavaScript
          run: npm run lint

  python_tests:
    name: Running python unit tests
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres
        env:
          POSTGRES_DB: hedera
          POSTGRES_USER: hedera
          POSTGRES_PASSWORD: hedera
        # Set health checks to wait until postgres has started
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          # Maps tcp port 5432 on service container to the host
          - 5432:5432
      redis:
        image: redis
        # Set health checks to wait until redis has started
        options: >-
          --health-cmd "redis-cli ping"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          # Maps port 6379 on service container to the host
          - 6379:6379

    steps:
        - uses: actions/checkout@v2

        - name: Setup Python
          uses: actions/setup-python@v2
          with:
            python-version: '3.10'

        - name: Setup Cache
          id: cache
          uses: actions/cache@v2
          with:
            path: ~/.cache/pip
            key: ${{ runner.os }}-pip-${{ hashFiles('**/**/requirements/dev.txt' ) }}
            restore-keys: |
              ${{ runner.os }}-pip-

        - name: Install Python Dependences
          run: |
            pip install wheel && \
            pip install -r hedera/requirements/base.txt && \
            pip install -r hedera/requirements/dev.txt

        - name: Run tests
          env:
            DJANGO_SETTINGS_MODULE: hedera.test_settings
          run: python manage.py test

  js_tests:
    name: Running javascript unit tests
    runs-on: ubuntu-latest

    steps:
        - uses: actions/checkout@v2

        - uses: actions/setup-node@v2
          with:
            node-version: '14'

        - name: Cache node modules
          uses: actions/cache@v2
          with:
            path: ~/.npm
            key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
            restore-keys: |
              ${{ runner.os }}-node-

        - name: Install Static Dependences
          run: npm i --include=dev

        - name: Run unit tests
          run: npm run test:unit
