name: Code Checks
on: [push]
jobs:
  qa:
    name: Checking Code
    runs-on: ubuntu-latest

    steps:
        - uses: actions/checkout@v2

        - name: Setup Python
          uses: actions/setup-python@v2
          with:
            python-version: 3.7

        - uses: actions/setup-node@v2
          with:
            node-version: '14'

        - name: Setup Cache
          id: cache
          uses: actions/cache@v2
          with:
            path: ~/.cache/pip
            key: ${{ runner.os }}-pip-${{ hashFiles('**/**/requirements/dev.txt' ) }}
            restore-keys: |
              ${{ runner.os }}-pip-

        - name: Setup flake8 annotations
          uses: rbialon/flake8-annotations@v1

        - name: Install Python Dependences
          run: |
            pip install -r hedera/requirements/dev.txt

        - name: Run linting and import sorting
          run: |
            isort -c **/*.py
            flake8 --show-source hedera lattices lemmatization lemmatized_text vocab_list lti

        - name: Install Static Dependences
          run: npm i --include=dev

        - name: Lint JavaScript
          run: npm run lint

  tests:
    name: Running unit tests
    runs-on: ubuntu-latest

    steps:
        - uses: actions/checkout@v2

        - name: Setup Python
          uses: actions/setup-python@v2
          with:
            python-version: 3.7

        - name: Setup Cache
          id: cache
          uses: actions/cache@v2
          with:
            path: ~/.cache/pip
            key: ${{ runner.os }}-pip-${{ hashFiles('**/**/requirements/dev.txt' ) }}
            restore-keys: |
              ${{ runner.os }}-pip-

        - name: Install Python Dependences
          run: |
            pip install -r hedera/requirements/base.txt && pip install -r hedera/requirements/dev.txt

        - name: Run tests
          run: |
            python manage.py test
